### ISSUE TITLE
Doesn't work on linux

### ISSUE THREAD

**Issue by aksh1618** [nikunjagarwal321/githeat-w2#1]
I get this error:

```
Enter full path and directory name
.
Traceback (most recent call last):
  File "githeat-w2.py", line 37, in <module>
    all_sub_size(input_path)
  File "githeat-w2.py", line 26, in all_sub_size
    size.append(os.path.getsize(curr_path))
  File "/usr/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '.\\README.md'
```

**Comment by nikunjagarwal321** [comment]
@aksh1618 I have tried to fix the issue. Please check once.

**Comment by aksh1618** [comment]
It works now for `.`, but no other directory.

**Comment by nikunjagarwal321** [comment]
I have corrected the mistake now.

**Comment by aksh1618** [comment]
Works now :+1:
