### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by aksh1618** [nikunjagarwal321/githeat-w2#2]
If I enter index of file, I get this:

```
Enter index of child directory
1
Traceback (most recent call last):
  File "githeat-w2.py", line 78, in <module>
    main()
  File "githeat-w2.py", line 64, in main
    get_all_sub_size(input_path)
  File "githeat-w2.py", line 19, in get_all_sub_size
    dir = os.listdir(parent_path)
NotADirectoryError: [Errno 20] Not a directory: '/home/aksh/Pictures/Arch.jpg'
```

**Comment by nikunjagarwal321** [comment]
The error came if we wanted to navigate a file instead of child-directory. I have tried to remove the error. Please check once.

**Comment by aksh1618** [comment]
Looks good.
